name: 'Python diff Coverage'
description: 'Check python code diff coverage'
inputs:
  compare_ref:
    description: 'The branch, tag or SHA to compare to'
    default: ${{ github.base_ref }}
  dir:
    description: 'Directory in which to run diff-cover'
    default: '.'
  report_dir:
    description: 'Directory containing coverage reports, relative to dir'
    default: '.'
  threshold:
    description: 'Coverage threshold'
    default: '100'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.compare_ref }}
    - ${{ inputs.dir }}
    - ${{ inputs.report_dir }}
    - ${{ inputs.threshold }}
